###
POST http://localhost:8088/api/survey
Content-Type: application/json

{
  "email": "test@test.com",
  "musicStyle": "Rock"
}

###
GET http://localhost:8088/api/survey
Content-Type: application/json

{
  "id": 0,
  "email": "",
  "musicStyle": ""
}


